export const allPosts = [
    {
        id: 1,
        title: 'Chicago Bulls',
        category: 'Deportes',
        text: 'Un texto sobre los Chicago Bulls',
        date: 1,
        author: 'user1',
        topSubject: 'Teams',
    },
    {
        id: 2,
        title: 'San Antonio Spurs',
        category: 'Deportes',
        text: 'Un texto sobre los Spurs de San Antonio',
        date: 8,
        author: 'user1',
        topSubject: 'Teams',
    },
    {
        id: 3,
        title: 'Los Angeles Lakers',
        category: 'Deportes',
        text: 'Un texto sobre los Lakers de Los Angeles',
        date: 2,
        author: 'user1',
        topSubject: 'Teams',
    },
    {
        id: 4,
        title: 'Boston Celtics',
        category: 'Deportes',
        text: 'Un texto sobre los Celtics de Boston',
        date: 1,
        author: 'user1',
        topSubject: 'Teams',
    },
    {
        id: 5,
        title: 'Betting lines',
        category: 'Deportes',
        text: 'Un texto sobre  betting lines',
        date: 9,
        author: 'user2',
        topSubject: 'Sports Bets',
    },
    {
        id: 6,
        title: 'Betting Results',
        category: 'Deportes',
        text: 'Un texto sobre betting results',
        date: 3,
        author: 'user1',
        topSubject: 'Sports Bets',
    },
    {
        id: 7,
        title: 'Michael Jordan',
        category: 'Deportes',
        text: 'Un texto sobre Michael Jordan',
        date: 1,
        author: 'user1',
        topSubject: 'Players',
    },
    {
        id: 8,
        title: 'Dallas Mavericks',
        category: 'Deportes',
        text: 'Un texto sobre los Mavs de Dallas',
        date: 8,
        author: 'user2',
        topSubject: 'Teams',
    },
    {
        id: 9,
        title: 'Tennis',
        category: 'Deportes',
        text: 'Un texto sobre el deporte blanco',
        date: 9,
        author: 'user1',
        topSubject: 'Other Sports',
    },
    {
        id: 10,
        title: 'Charles Barkley',
        text: 'Aqui va algo sobre sir Charles',
        date: 10,
        author: 'user1',
        topSubject: 'Players',
    },
];

export const allUsers = [
    {
        id: 1,
        name: 'CarliC',
        messages: [],
        registered: 1,
    },
    {
        id: 1,
        name: 'Jane',
        messages: [],
        registered: 2,
    },
    {
        id: 3,
        name: 'John',
        messages: [],
        registered: 3,
    },
];